FROM mminke/apache-tomcat-7.0.50
MAINTAINER Francesco Strozzi
ADD owlim-lite/sesame_owlim/openrdf-sesame.war /opt/apache-tomcat-7.0.50/webapps/openrdf-sesame.war
ADD owlim-lite/sesame_owlim/openrdf-workbench.war /opt/apache-tomcat-7.0.50/webapps/openrdf-workbench.war

EXPOSE 8080
